#!/usr/bin/env python3
"""Separate unit means from spreads in the baseline Gaussian reconstruction.

Reads results/gauss_reconstruction.csv, generated by gauss_reconstruction.py.
Each curve averages -log(participation) across runs, not participation before
taking the logarithm. Moment substitutions are not interventions on training.
Usage: PYTHONPATH=src python scripts/figures/fig8b_gaussian_ablations.py
"""
from pathlib import Path
import numpy as np
import pandas as pd
import _figlib as F
from _figlib import S


def main():
    args = F.parse(__doc__)
    S.use_style()
    data = pd.read_csv(Path(args.results) / "gauss_reconstruction.csv")
    methods = [
        ("p_meas", "Measured", S.INK, "-", "o"),
        ("p_gauss", "Full Gaussian", S.color(2), "-", None),
        ("p_shared_spread", "Shared spread", S.color(6), "--", None),
        ("p_zero_mean", "Zero means", S.color(1), ":", None),
    ]
    fig, axes = S.plt.subplots(1, 3, figsize=(S.FULL_WIDTH, 2.25))
    for layer, ax in enumerate(axes, 1):
        subset = data[data.layer == layer].copy()
        if subset.empty:
            raise ValueError(f"Missing layer {layer} in Gaussian reconstruction")
        for key, label, color, style, marker in methods:
            subset[key] = -np.log(subset[key])
            mean = subset.groupby("step")[key].mean()
            ax.plot(mean.index, mean, color=color, ls=style, marker=marker,
                    ms=3, lw=1.5, label=label)
        ax.set_xscale("symlog", linthresh=100)
        ax.set_xticks([0, 100, 500, 3000], ["0", "100", "500", "3000"])
        ax.set_xlabel("step")
        ax.set_ylim(bottom=0)
        S.panel_title(ax, "abc"[layer - 1], f"layer {layer}")
    axes[0].set_ylabel(r"participation loss $-\log p_\ell$")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, ncol=4, loc="lower center", bbox_to_anchor=(0.5, -0.015))
    fig.subplots_adjust(left=0.07, right=0.99, bottom=0.30, top=0.89, wspace=0.30)
    S.save(fig, "fig8b_gaussian_ablations", root=args.out_root)


if __name__ == "__main__":
    main()
