#!/usr/bin/env python3
"""Check reduced-model quadrature and Euler resolution in three selected settings.

Run with --rebuild-init to reconstruct the saved initial states from image data.
The default reuses the archived states, requiring no images or training logs.
"""
import argparse
from dataclasses import asdict, replace
import hashlib
import json
from pathlib import Path
import sys
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'src'))
from cmc import reduced as R

CASES=[('Baseline','E1_headline/base'),('Gain 10','E2_master/g10.0'),
       ('Width 100, depth 7','E17_grid/w100_d7')]


def serial(value):
    if isinstance(value,np.ndarray):return value.tolist()
    if isinstance(value,np.generic):return value.item()
    raise TypeError(type(value).__name__)


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--rebuild-init',action='store_true')
    args=p.parse_args();dest=ROOT/'results/review_resolution';dest.mkdir(exist_ok=True)
    initial=dest/'initial_states.json'
    if args.rebuild_init:
        import torch
        torch.set_num_threads(2)
        cases=[]
        for label,relative in CASES:
            path=ROOT/'results'/relative/'seed0_fb0.meta.json'
            init,cfg,feedback=R.init_from_meta(json.loads(path.read_text()))
            cases.append(dict(label=label,source=str(path.relative_to(ROOT)),
                              metadata_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                              init=asdict(init),config=asdict(cfg),feedback=feedback))
        initial.write_text(json.dumps(cases,default=serial,indent=2)+'\n')
    cases=json.loads(initial.read_text());records=[];summary=[]
    old_nodes,old_weights=R.GH_X,R.GH_W
    try:
        for case in cases:
            state=case['init'].copy()
            state['mu0']=[np.asarray(v) for v in state['mu0']]
            for k in ('zbar0','tbar'):state[k]=np.asarray(state[k])
            init=R.Init(**state);cfg=R.ReducedConfig(**case['config'])
            feedback=[np.asarray(v) for v in case['feedback']];rows=[]
            for nodes,substeps in [(64,1),(32,1),(128,1),(64,2),(64,4)]:
                R.GH_X,R.GH_W=np.polynomial.hermite.hermgauss(nodes)
                d=R.simulate(init,replace(cfg,substeps=substeps),feedback)
                rows.append(dict(label=case['label'],nodes=nodes,substeps=substeps,
                                 horizon=cfg.steps,onset=d.attrs['onset'],exit=d.attrs['exit'],
                                 min_participation=[float(d.loc[d.step<=300,f'p_l{i}'].min())
                                                    for i in range(1,len(init.widths)+1)]))
            base=rows[0];fine=rows[-1]
            summary.append(dict(label=case['label'],exit_one=base['exit'],exit_two=rows[-2]['exit'],
                                exit_four=fine['exit'],max_participation_change=float(np.max(np.abs(
                                    np.array(base['min_participation'])-fine['min_participation']))),
                                max_quadrature_change=max(float(np.max(np.abs(np.array(base['min_participation'])-r['min_participation']))) for r in rows[1:3])))
            records.extend(rows)
    finally:
        R.GH_X,R.GH_W=old_nodes,old_weights
    source_files=['src/cmc/reduced.py','scripts/review_resolution.py']
    output=dict(protocol=dict(seed=0,feedback_seed=0,participation_window=300,
                              quadrature_orders=[32,64,128],euler_substeps=[1,2,4],
                              initialization_sha256=hashlib.sha256(initial.read_bytes()).hexdigest(),
                              source_sha256={f:hashlib.sha256((ROOT/f).read_bytes()).hexdigest() for f in source_files}),
                records=records,summary=summary)
    (dest/'resolution.json').write_text(json.dumps(output,indent=2)+'\n')
    lines=[r'% Generated by scripts/review_resolution.py.',r'\begin{table}[t]\centering\small',
           r'\caption{Numerical resolution in three selected settings, each with initialization/feedback seeds $(0,0)$. Exit is in update steps for one, two or four Euler substeps. The last column is the largest absolute change in the first-300-update participation minimum across layers from one to four substeps. These use 64 quadrature nodes; orders 32 and 128 give the same displayed minima and timing. All detailed values and initial states accompany the code.}\label{tab:resolution}',
           r'\begin{tabular}{lrrrr}\toprule Setting & Exit: 1 & 2 & 4 & Max. $|\Delta\min p_\ell|$\\\midrule']
    for s in summary:
        lines.append(' & '.join([s['label'],str(s['exit_one']),str(s['exit_two']),str(s['exit_four']),f"{s['max_participation_change']:.4f}"])+r'\\')
    lines.append(r'\bottomrule\end{tabular}\end{table}')
    (ROOT/'paper/tables/review_resolution.tex').write_text('\n'.join(lines)+'\n')
    print(json.dumps(summary,indent=2))


if __name__=='__main__':main()
