#!/usr/bin/env python3
"""Auditable reporting for the September review: cohorts, windows and uncertainty."""
import json
from pathlib import Path
import sys
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];DEST=ROOT/'results/review_20260919'
sys.path.insert(0,str(ROOT/'src'))


def pm(values,decimals=2):
    v=pd.Series(values,dtype=float).dropna()
    if not len(v):return '--'
    return f'${v.mean():.{decimals}f}'+(rf'\pm{v.std():.{decimals}f}' if len(v)>1 else '')+'$'


def table(name,caption,label,headers,rows):
    if name in {'E7','E8'}:
        out=[r'% Generated by scripts/review_reporting.py.',r'\begingroup\scriptsize\setlength{\tabcolsep}{3.5pt}',
             r'\begin{longtable}{l'+'r'*(len(headers)-1)+'}',rf'\caption{{{caption}}}\label{{{label}}}\\',
             r'\toprule',' & '.join(headers)+r'\\\midrule\endfirsthead',
             r'\toprule',' & '.join(headers)+r'\\\midrule\endhead',r'\bottomrule\endfoot']
        out+=[' & '.join(map(str,row))+r'\\' for row in rows]
        out+=[r'\end{longtable}\endgroup']
    else:
        out=[r'% Generated by scripts/review_reporting.py.',r'\begin{table}[t]\centering\scriptsize\setlength{\tabcolsep}{3.5pt}',
             rf'\caption{{{caption}}}\label{{{label}}}',r'\begin{tabular}{l'+'r'*(len(headers)-1)+'}',
             r'\toprule',' & '.join(headers)+r'\\\midrule']
        out+=[' & '.join(map(str,row))+r'\\' for row in rows]
        out+=[r'\bottomrule\end{tabular}\end{table}']
    (ROOT/'paper/tables'/f'{name}.tex').write_text('\n'.join(out)+'\n')



def sustained_crossing(df,threshold,hold=50):
    """First logged loss crossing maintained at every log for at least hold steps."""
    good=(df.probe_loss<threshold).to_numpy();s=df.step.to_numpy()
    for i in np.flatnonzero(good):
        j=np.searchsorted(s,s[i]+hold)
        if j<len(s) and good[i:j+1].all():return float(s[i])
    return np.nan


def cluster_summary(df,draws=2000):
    """Percentile bootstrap of entire physical conditions, retaining their seeds/layers."""
    groups=[g[['p_model','p_meas']].dropna().to_numpy() for _,g in df.groupby(['exp','tag'])]
    def moments(a):
        x,y=a.T;return [len(a),x.sum(),y.sum(),(x*x).sum(),(y*y).sum(),(x*y).sum(),abs(x-y).sum()]
    m=np.array([moments(g) for g in groups]);rng=np.random.default_rng(190919)
    def calc(t):
        n,x,y,xx,yy,xy,ae=np.moveaxis(t,-1,0)
        return (n*xy-x*y)/np.sqrt(np.maximum((n*xx-x*x)*(n*yy-y*y),1e-30)),ae/n
    r,mae=calc(m.sum(0));boot=m[rng.integers(len(m),size=(draws,len(m)))].sum(1);rr,ee=calc(boot)
    return dict(n_conditions=len(m),n_points=sum(map(len,groups)),r=float(r),mae=float(mae),
                r_ci=np.quantile(rr,[.025,.975]).tolist(),mae_ci=np.quantile(ee,[.025,.975]).tolist())


def main():
    DEST.mkdir(exist_ok=True);summary={}
    model=pd.read_csv(ROOT/'results/reduced_crossseed.csv')
    modes={'Pooled':model,'Condition means':model.groupby(['exp','tag'],as_index=False)[['p_model','p_meas']].mean()}
    modes.update({f'Layer {l}':g for l,g in model.groupby('layer')})
    records={k:cluster_summary(v) for k,v in modes.items()}
    rows=[]
    for name,r in records.items():
        ci='--' if r['n_conditions']<3 else f"$[{r['r_ci'][0]:.2f},{r['r_ci'][1]:.2f}]$"
        rows.append([name,r['n_conditions'],r['n_points'],f"{r['r']:.2f}",ci,f"{r['mae']:.3f}"])
    table('review_model_stats','Participation prediction across distinct physical conditions. Intervals resample whole conditions, retaining their seed and layer observations (2,000 bootstrap draws). Condition means average over seeds and layers; deeper layers contain only two conditions and have no reported interval.','tab:review_model_stats',['Summary','Conditions','Points','$r$','95\\% interval','MAE'],rows)
    (DEST/'grouped_model.json').write_text(json.dumps(records,indent=2)+'\n')
    summary.update(ConditionR=records['Condition means']['r'],ConditionCI='--'.join(f'{v:.2f}' for v in records['Condition means']['r_ci']),
                   PooledCI='--'.join(f'{v:.2f}' for v in records['Pooled']['r_ci']))
    timing=[]
    for exp,tags in [('E13_adam',['sgd_base','adam0.001_base','adam0.0001_base']),
                     ('E4_cures',['base__none','base__whiten','base__whiten_lam3.0','base__whiten_lam10.0'])]:
        for tag in tags:
            for f in sorted((ROOT/'results'/exp/tag).glob('seed*_fb*.csv')):
                d=pd.read_csv(f);m=json.loads(f.with_suffix('.meta.json').read_text())
                timing.append(dict(exp=exp,tag=tag,seed=m['seed'],time=sustained_crossing(d,.9*m['prior_loss']),
                                   accuracy=float(d.probe_acc.iloc[-1])))
    t=pd.DataFrame(timing);t.to_csv(DEST/'learning_times.csv',index=False)
    # Both families replay the same SGD baseline; show it once, without pooling seeds.
    baseline=t[t.tag=='sgd_base'].sort_values('seed')[['time','accuracy']].to_numpy()
    repeated=t[t.tag=='base__none'].sort_values('seed')[['time','accuracy']].to_numpy()
    if baseline.shape != repeated.shape or not np.allclose(baseline,repeated,equal_nan=True):
        raise ValueError('The two SGD baseline cohorts differ; do not silently merge them.')
    timing_labels={'sgd_base':'Plain SGD', 'adam0.001_base':r'Adam, $\eta=10^{-3}$',
                   'adam0.0001_base':r'Adam, $\eta=10^{-4}$',
                   'base__whiten':r'Conditioner, $\lambda_{\rm rel}=0.1$',
                   'base__whiten_lam3.0':r'Conditioner, $\lambda_{\rm rel}=3$',
                   'base__whiten_lam10.0':r'Conditioner, $\lambda_{\rm rel}=10$'}
    table('review_timing','Learning time without requiring a detected plateau: first probe loss below 90\\% of the constant-predictor loss, remaining below it for 50 updates. All runs use the same criterion and seed pairs $(0,0)$, $(1,1)$ and $(2,2)$; the shared SGD baseline is shown once, so its accuracy can differ slightly from the 15-trajectory value in Table~\\ref{tab:E1}. Values are means $\\pm$ standard deviations; counts state how many reach it within 3,000 updates.','tab:review_timing',['Condition','$n$','Time','Reached/$n$','Final accuracy'],
          [[label,len(g),pm(g.time,0),f'{g.time.notna().sum()}/{len(g)}',pm(g.accuracy,3)]
           for tag,label in timing_labels.items() for g in [t[t.tag==tag]]])
    for tag,key in [('sgd_base','SGDLearn'),('adam0.001_base','AdamLearn'),('adam0.0001_base','AdamSlowLearn')]:summary[key]=float(t.loc[t.tag==tag,'time'].mean())
    from scipy.stats import spearmanr
    drift=[]
    for file in sorted((ROOT/'results/E1_headline/base').glob('seed*_fb*.snapshots.npz')):
        with np.load(file) as z:
            for layer in [1,2,3]:
                drift.append(dict(run=file.stem,layer=layer,
                    spearman=float(spearmanr(z[f'step0/B1_l{layer}'],z[f'step120/mu_l{layer}']-z[f'step0/mu_l{layer}']).statistic)))
    dd=pd.DataFrame(drift);dd.to_csv(DEST/'unit_drift.csv',index=False)
    table('review_unit_drift','Unit mean shifts from initialization to step 120 against the shared-error feedback coefficient. Values are means and standard deviations of per-run Spearman correlations across the 15 baseline trajectories (five initializations crossed with three feedback draws); they are descriptive spreads, not independent-run confidence intervals.',
          'tab:review_unit_drift',['Layer','Trajectories','Spearman correlation'],
          [[l,len(g),pm(g.spearman)] for l,g in dd.groupby('layer')])
    # Anatomy is reported at the same checkpoint for both covariance measures.
    anatomy=[]
    for f in sorted((ROOT/'results/E7_anatomy').glob('*/seed*_fb*.csv')):
        d=pd.read_csv(f);q=d[(d.step>=30)&d.R_l3.notna()].dropna(subset=['lam_l3'])
        ix=q.lam_l3.idxmin();row=d.loc[ix];start=d.iloc[0]
        anatomy.append(dict(tag=f.parent.name,step=row.step,energy_drop=start.lam_l3/row.lam_l3,
                            R_initial=start.R_l3,R_matched=row.R_l3,R_drop=start.R_l3/row.R_l3,
                            direction_fraction=row.get('r1frac_l3',np.nan),gradient_cosine=row.get('cosA_l3',np.nan)))
    a=pd.DataFrame(anatomy);a.to_csv(DEST/'anatomy_matched.csv',index=False)
    table('E7','Layer-3 covariance and update diagnostics. Within each run, $t_*\\ge30$ minimizes covariance energy among checkpoints with a recorded normalized statistic $R_3$. The energy ratio is $\\|\\Lambda_3(0)\\|_F^2/\\|\\Lambda_3(t_*)\\|_F^2$; all noninitial quantities use that checkpoint. The direction fraction is the proportion of centered preactivation variance along the initial mean-error feedback direction; it is not an update fraction. The final column is gradient cosine; -- means not recorded. $R_3$ is a probe covariance statistic, not held-out accuracy.','tab:E7',
          ['Condition','$n$','$t_*$','Energy ratio','$R_3(0)$','$R_3(t_*)$','Direction fraction','$\\cos\\alpha_*$'],
          [[tag.replace('_',r'\_'),len(g),pm(g.step,0),pm(g.energy_drop,1),pm(g.R_initial),pm(g.R_matched),pm(g.direction_fraction),pm(g.gradient_cosine)] for tag,g in a.groupby('tag')])
    summary['MatchedCovDrop']=float(a.loc[a.tag=='base','energy_drop'].mean());summary['MatchedRDrop']=float(a.loc[a.tag=='base','R_drop'].mean())
    shifts=[]
    for f in sorted((ROOT/'results/E8_shift').glob('*/seed*_fb*.csv')):
        d=pd.read_csv(f);m=json.loads(f.with_suffix('.meta.json').read_text());s=int(m.get('shift_step',1500) or 1500)
        pre=d[(d.step>=s-100)&(d.step<s)];post=d[(d.step>=s)&(d.step<=s+300)]
        if not len(post):continue
        shifts.append(dict(tag=f.parent.name,seed=m['seed'],shift=s,cos_pre=pre.cos_l3.max(),cos_post=post.cos_l3.max(),
                           p_pre=pre.p_l3.min(),p_post=post.p_l3.min(),
                           error_first=float(post.batch_ebar_norm.iloc[0]),
                           error_fifty=float(d.loc[d.step==s+50,'batch_ebar_norm'].iloc[0]),
                           balanced_at_shift=float(d.loc[d.step==s,'probe_bal_acc'].iloc[0]),
                           balanced_after_250=float(d.loc[d.step==s+250,'probe_bal_acc'].iloc[0]),
                           final_balanced_accuracy=float(d.probe_bal_acc.iloc[-1])))
    sh=pd.DataFrame(shifts);sh.to_csv(DEST/'shift_windows.csv',index=False)
    table('E8','Label-prior shift: top-layer geometry during the 100 updates before the shift and the first 300 updates after it. Error norms use the first shifted training batch and the batch 50 updates later. The fixed validation probe retains its pre-shift distribution; these geometry measurements do not use a newly imbalanced probe.','tab:E8',
          ['Condition','$n$','Shift','Peak cos. before','after','Min. $p$ before','after','$\\|\\bar e\\|$: first / +50'],
          [[tag.replace('_',r'\_'),len(g),str(int(g['shift'].iloc[0])),pm(g.cos_pre),pm(g.cos_post),pm(g.p_pre),pm(g.p_post),f'{g.error_first.mean():.3f} / {g.error_fifty.mean():.3f}'] for tag,g in sh.groupby('tag')])
    # Matched preprocessing/readout evidence already exists; use a common horizon.
    heads=[]
    for exp,tag,label in [('E13_adam','sgd_base','Raw pixels, sigmoid'),('E16_batch','mnist_b128','Raw pixels, softmax'),
                          ('E7_anatomy','softmax','Standardized, softmax')]:
        for f in sorted((ROOT/'results'/exp/tag).glob('seed*_fb*.csv')):
            d=pd.read_csv(f);m=json.loads(f.with_suffix('.meta.json').read_text());q=d[d.step<=1500]
            heads.append(dict(label=label,seed=m['seed'],preprocess=m['preprocess'],head=m['head'],
                              error=d.ebar_norm.iloc[0],cos=q.cos_l3.max(),p=q[q.step<=300].p_l3.min()))
    h=pd.DataFrame(heads);h.to_csv(DEST/'matched_heads.csv',index=False)
    table('review_heads','MNIST readout comparisons with preprocessing stated explicitly. All rows use the same three initialization--feedback pairs, $(0,0)$, $(1,1)$ and $(2,2)$, batch size 128, and a 1,500-update window for peak cosine; participation minima use the first 300 updates. These are the first three of the 15 headline trajectories, so values can differ slightly from Table~\\ref{tab:E1}. Only the first two rows isolate the readout choice.','tab:review_heads',
          ['Protocol','$n$','Initial $\\|\\bar e\\|$','Peak cosine','Min. $p_3$'],
          [[label,len(g),pm(g.error,3),pm(g.cos,3),pm(g.p,3)] for label,g in h.groupby('label',sort=False)])
    summary['RawSoftmaxCos']=float(h[h.label=='Raw pixels, softmax']['cos'].mean())
    # Snapshot readout checks use distinct fitting and evaluation splits.
    d=pd.read_csv(DEST/'decoders.csv');r=pd.read_csv(DEST/'readouts.csv')
    table('review_features','Frozen-feature diagnostics with 10,000 training examples for fitting and 5,000 separate validation examples for evaluation. A fixed trace-relative ridge of $10^{-3}$ is used for least-squares one-hot decoding. Here $R$ uses the fitting set and decoder ridge, whereas Table~\\ref{tab:E7} uses the probe estimator. The collapse checkpoint is each run\'s layer-3 participation minimum within its first 300 updates. Values average three seeds.','tab:review_features',
          ['Checkpoint','Layer','Covariance energy','$R$','Feature RMS','Decoder accuracy'],
          [[c,l,pm(g.cov_energy,3),pm(g.normalized_covariance,2),pm(g.rms,3),pm(g.heldout_accuracy,3)] for (c,l),g in d.groupby(['checkpoint','layer'],sort=False)])
    for checkpoint,key in [('initial','InitialDecode'),('collapse','CollapseDecode'),('recovery','RecoveryDecode')]:summary[key]=100*float(d[(d.checkpoint==checkpoint)&(d.layer==3)].heldout_accuracy.mean())
    for control,key in [('raw','FrozenRaw'),('centered','FrozenCentered'),('scaled','FrozenScaled')]:summary[key]=100*float(r[(r.checkpoint=='collapse')&(r.readout==control)&(r.step==3000)].accuracy.mean())
    # Signed directional budgets and their sparse, path-length-weighted summaries.
    h=pd.read_csv(ROOT/'results/revision_dynamics/drift.csv');h=h[(h.config=='base')&(h.layer==3)].copy()
    for col in [c for c in h if c.endswith('_projection')]:h[col]=h[col]/h.actual_norm
    b=pd.read_csv(DEST/'readout_budget.csv');budget_rows=[];integrated=[]
    for frame,label in [(h,'Hidden layer 3'),(b,'Readout')]:
        for step in [0,50,100,300]:
            g=frame[frame.step==step]
            budget_rows.append([label,step,pm(g.leading_projection),pm(g.upstream_projection),pm(g.covariance_projection),pm(g.actual_norm,4)])
        for seed,g in frame[frame.step<=100].groupby('seed'):
            g=g.sort_values('step');den=np.trapezoid(g.actual_norm,g.step)
            integrated.append(dict(part=label,seed=seed,**{c:float(np.trapezoid(g[c]*g.actual_norm,g.step)/den) for c in frame if c.endswith('_projection')}))
    pd.DataFrame(integrated).to_csv(DEST/'integrated_drift.csv',index=False)
    table('review_drift','Signed projections onto the measured virtual mean displacement, divided by its squared norm. The complete components sum to one; the displayed columns omit the gate residual or output-map error and the finite cross term, so they need not sum to one. Absolute displacement norms are shown because large fractions can arise when net motion is small. Means and standard deviations use three seeds.','tab:review_drift',
          ['Location','Step','Mean term','Upstream','Covariance','$\\|\\Delta\\mu\\|$ or $\\|\\Delta\\bar z\\|$'],budget_rows)
    summary.update(HiddenUpstreamInitial=float(h[h.step==0].upstream_projection.mean()),
                   HiddenMeanFifty=float(h[h.step==50].leading_projection.mean()),
                   ReadoutMeanFifty=float(b[b.step==50].leading_projection.mean()))
    # Majority references and balanced accuracy for imbalanced image controls.
    imbalance=[]
    for exp in ['E1_headline','E11_cifar','E12_cifar2']:
        for f in sorted((ROOT/'results'/exp).glob('*/seed*_fb*.csv')):
            meta=json.loads(f.with_suffix('.meta.json').read_text())
            if meta.get('p0',0)<=0:continue
            run=pd.read_csv(f)
            imbalance.append(dict(experiment=exp,tag=f.parent.name,seed=meta['seed'],fb_seed=meta['fb_seed'],
                                  majority=max(meta['prior']),accuracy=run.probe_acc.iloc[-1],balanced=run.probe_bal_acc.iloc[-1]))
    im=pd.DataFrame(imbalance);im.to_csv(DEST/'imbalanced_accuracy.csv',index=False)
    imbalance_labels={'cnn_softmax_imb07':'CIFAR-10, DFA', 'cnn_softmax_imb07_bp':'CIFAR-10, BP',
                      'cnn_softmax_imb07_centere':'CIFAR-10, centered error',
                      'softmax_imb07':'MNIST, DFA', 'softmax_imb07_bp':'MNIST, BP'}
    table('review_imbalance','Imbalanced softmax controls at their final recorded update (MNIST: 3000; CIFAR-10: 4000). The majority-class reference uses the training sampling prior; balanced accuracy averages class recall on the fixed probe. Raw accuracy alone can be close to the majority predictor.','tab:review_imbalance',
          ['Dataset / rule','$n$','Majority reference','Accuracy','Balanced accuracy'],
          [[imbalance_labels[tag],len(g),pm(g.majority),pm(g.accuracy),pm(g.balanced)]
           for (e,tag),g in im.groupby(['experiment','tag'])])
    # Collapse redundant SGD gain/rate combinations before fitting recovery times.
    rr=pd.read_csv(ROOT/'results/E5_recovery/summary_per_run.csv')
    rr['a']=(rr.lr*rr.hid_lr_mult*rr.fb_scale).round(12)
    rr['eta_out']=(rr.lr*rr.out_lr_mult).round(12)
    rr=rr.drop_duplicates(['a','eta_out','seed','fb_seed'])
    valid=rr[(rr.plateau_duration>0)&(rr.a>0)&(rr.eta_out>0)].copy()
    def fit_rates(frame):
        X=np.column_stack([np.ones(len(frame)),np.log(frame.a),np.log(frame.eta_out)])
        y=np.log(frame.plateau_duration);coef=np.linalg.lstsq(X,y,rcond=None)[0]
        return coef,1-((y-X@coef)**2).sum()/((y-y.mean())**2).sum()
    coef,r2=fit_rates(valid);groups=[g for _,g in valid.groupby(['a','eta_out'])]
    rng=np.random.default_rng(190919)
    boot=np.array([fit_rates(pd.concat([groups[i] for i in rng.integers(len(groups),size=len(groups))]))[0]
                   for _ in range(2000)])
    ci=np.quantile(boot[:,1:],[.025,.975],axis=0)
    fit=dict(runs=len(valid),eligible_runs=len(rr),conditions=len(groups),exponents=coef[1:].tolist(),r2=float(r2),ci=ci.tolist())
    (DEST/'two_rate_recovery.json').write_text(json.dumps(fit,indent=2)+'\n')
    valid.to_csv(DEST/'two_rate_recovery.csv',index=False)
    summary.update(RateHid=coef[1],RateOut=coef[2],RateRtwo=r2,RateRuns=len(valid),RateEligible=len(rr))
    table('review_rate_fit','Two-rate recovery fit after merging equivalent SGD gain/rate settings. The fit is conditional on observed plateau durations; intervals resample whole effective-rate conditions (2,000 draws).',
          'tab:review_rate_fit',['Predictor','Exponent','95\\% interval'],
          [[r'$a=\eta_{\rm hid}g$',f'{coef[1]:.2f}',f'[{ci[0,0]:.2f}, {ci[1,0]:.2f}]'],
           [r'$\eta_{\rm out}$',f'{coef[2]:.2f}',f'[{ci[0,1]:.2f}, {ci[1,1]:.2f}]']])
    af=DEST/'recovery_ablations.csv'
    if af.exists():
        a=pd.read_csv(af);rows=[]
        for (family,variant),g in a.groupby(['family','variant'],sort=False):
            both=g.onset_network.notna()&g.onset_model.notna();pairs=g.dropna(subset=['exit_network','exit_model'])
            rows.append([family+' / '+variant.replace('_',' '),len(g),int(both.sum()),
                         int((g.onset_network.notna()&g.onset_model.isna()).sum()),int((g.onset_network.isna()&g.onset_model.notna()).sum()),
                         f'{len(pairs)}/{int(g.exit_network.notna().sum())}',
                         '--' if len(pairs)==0 else f'{np.median(abs(pairs.exit_model-pairs.exit_network)/pairs.exit_network):.2f}'])
        table('review_recovery','Recovery alternatives at each network\'s recorded training horizon. Both, missed and extra refer to plateau onset detection. Exit pairs count observed model/network exits relative to all observed network exits; timing error is conditional on paired exits. Each variant uses the same collapse trajectory and detector. The fresh group uses new width/depth combinations and seeds, with predictions saved before training.','tab:review_recovery',
              ['Group / variant','Runs','Both','Missed','Extra','Exit pairs','Median rel. error'],rows)
        windows=[]
        for file in sorted((DEST/'model').glob('sweeps_*.json')):   # sorted: deterministic summation order
            data=json.loads(file.read_text());identity={k:data['records'][0][k] for k in ['exp','tag','seed','fb_seed']}
            for row in data['windows']:windows.append(dict(**identity,**row))
        w=pd.DataFrame(windows);w.to_csv(DEST/'window_sensitivity.csv',index=False)
        # Each run/layer appears twice, even if the rescaled and fixed windows coincide.
        w['type']=np.tile(['fixed','rescaled'],len(w)//2)
        for typ,g in w.groupby('type'):
            summary['Window'+typ.title()+'R']=float(g.p_model.corr(g.p_network))
            summary['Window'+typ.title()+'MAE']=float(abs(g.p_model-g.p_network).mean())
    (DEST/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
    print(json.dumps(summary,indent=2))


if __name__=='__main__':main()
