#!/usr/bin/env python3
"""Generate complete control and residual tables from the saved measurements."""
from pathlib import Path
import json
import numpy as np
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]


def pm(series,decimals=3):
    v=series.dropna()
    if not len(v):return "--"
    return f"${v.mean():.{decimals}f}\\pm{v.std():.{decimals}f}$" if len(v)>1 else f"${v.mean():.{decimals}f}$"


def main():
    r=pd.read_csv(ROOT/"results/revision_per_run.csv")
    lines=[r"% Generated by scripts/revision_tables.py from results/revision_per_run.csv.",
           r"\begingroup\small\setlength{\tabcolsep}{3.5pt}",
           r"\begin{longtable}{lrrrrrr}",
           r"\caption{Optimizer, feedback, activation, batch-size and network-size controls. Each row uses three initialization--feedback pairs. Peak cosine and participation are measured in the deepest layer; participation minima use the first 300 steps. Exit averages include only observed exits, with their count shown explicitly. An undetected plateau is not assigned zero duration. In the batch-size block, MNIST uses raw pixels with softmax; CIFAR-10 uses calibrated sigmoid outputs.}\label{tab:revision_controls}\\",
           r"\toprule Condition & $n$ & Peak cosine & Min. $p_L$ & Exit & Exits/$n$ & Final accuracy\\\midrule\endfirsthead",
           r"\toprule Condition & $n$ & Peak cosine & Min. $p_L$ & Exit & Exits/$n$ & Final accuracy\\\midrule\endhead",
           r"\bottomrule\endfoot"]
    for family,frame in r.groupby("family",sort=True):
        if family == "E17_grid": lines.append(r"\newpage")
        title={"E13_adam":"Optimizer comparisons (3,000 updates)","E14_controls":"Feedback and activation controls (3,000 updates)",
               "E15_cifar100":"CIFAR-100 (3,000 updates)","E16_batch":"Near-zero-error readouts (1,500 updates)","E17_grid":"Width and depth (3,000 updates)"}[family]
        lines.append(r"\multicolumn{7}{l}{\textbf{"+title+r"}}\\")
        for tag,g in frame.groupby("tag",sort=True):
            label=tag.replace("_",r"\_")
            lines.append(f"{label} & {len(g)} & {pm(g.maxcos)} & {pm(g.minp)} & {pm(g.exit,0)} & {g.exit.notna().sum()}/{len(g)} & {pm(g.acc_final)} \\\\")
        lines.append(r"\addlinespace")
    if lines[-1] == r"\addlinespace": lines.pop()
    lines += [r"\end{longtable}\endgroup"]
    (ROOT/"paper/tables/revision_controls.tex").write_text("\n".join(lines)+"\n")
    coverage=[r"% Generated from reduced_crossseed.json and reduced_grid.json.",
              r"\begin{table}[t]\centering\scriptsize",
              r"\caption{Plateau detection and timing coverage. Both, network only, model only and neither partition all trajectories by detected onset. Censored model exits are included in Both but excluded from numerical exit errors. Plateau detection uses loss, not hidden-state collapse.}\label{tab:model_coverage}",
              r"\begin{tabular}{lrrrrrrr}\toprule Comparison & Runs & Both & Network only & Model only & Neither & Exit pairs & Censored\\\midrule"]
    for name,label in (("reduced_crossseed","Parameter sweeps"),("reduced_grid","Width--depth grid")):
        d=json.loads((ROOT/f"results/{name}.json").read_text())
        values=[d[k] for k in ("n_trajectories","n_both_plateau","n_network_only_plateau","n_model_only_plateau","n_neither_plateau","exit_valid_n","exit_censored_n")]
        coverage.append(label+" & "+" & ".join(map(str,values))+r"\\")
    coverage += [r"\bottomrule\end{tabular}\end{table}"]
    (ROOT/"paper/tables/revision_model_coverage.tex").write_text("\n".join(coverage)+"\n")
    d=pd.read_csv(ROOT/"results/revision_dynamics/residual.csv")
    lines=[r"% Generated from results/revision_dynamics/residual.csv.",r"\begin{table}[t]\centering\small",
           r"\caption{Gate--error residual norm relative to the leading mean-teaching norm, mean $\pm$ standard deviation over three seed pairs. Absolute norms are retained in the supplementary data.}\label{tab:residual_replication}",
           r"\begin{tabular}{llrrr}\toprule Setting & Step & Layer 1 & Layer 2 & Layer 3\\\midrule"]
    for setting,label in (("base","MNIST tanh"),("relu","MNIST ReLU"),("cifar_mlp","CIFAR-10 tanh")):
        for step in (0,50,100,300):
            g=d[(d.config==setting)&(d.step==step)]
            vals=" & ".join(pm(g[g.layer==l].ratio,2) for l in (1,2,3))
            lines.append(f"{label if step==0 else ''} & {step} & {vals} \\\\")
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (ROOT/"paper/tables/revision_residuals.tex").write_text("\n".join(lines)+"\n")


if __name__=="__main__":main()
