#!/usr/bin/env python3
"""Summarize every experiment under results/: writes results/<exp>/summary.csv and summary_per_run.csv, and one
markdown table per experiment into results/SUMMARY.md.

Usage: PYTHONPATH=src python3 scripts/summarize_all.py [--results results] [--window 300] [--exp E1_headline ...]
"""
from __future__ import annotations
import argparse, datetime, os, sys, traceback

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
from cmc import analysis as A


def parse_args():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default=os.path.join(ROOT, "results"), help="results root")
    ap.add_argument("--window", type=int, default=A.P_WINDOW, help="participation minima are windowed to step <= this")
    ap.add_argument("--exp", nargs="*", default=None, help="only these experiment names (default: all)")
    ap.add_argument("--out", default=None, help="markdown file (default: <results>/SUMMARY.md)")
    return ap.parse_args()


def main():
    args = parse_args()
    root = os.path.abspath(args.results)
    dirs = A.experiment_dirs(root)
    if args.exp: dirs = [d for d in dirs if os.path.basename(d) in args.exp]
    if not dirs:
        print(f"no experiment directories under {root}"); return 1
    out_md = args.out or os.path.join(root, "SUMMARY.md")
    blocks, done = [], 0
    for d in dirs:
        exp = os.path.basename(d)
        print(f"[{exp}]")
        try:
            res = A.summarize_and_write(d, window=args.window)
        except Exception:                                   # a half-written experiment must not stop the others
            print(f"  failed to summarize {exp}:"); traceback.print_exc(limit=2); continue
        if res is None:
            print("  no finished runs yet"); continue
        per, agg = res
        done += 1
        print(f"  {len(per)} runs, {len(agg)} tags -> summary.csv, summary_per_run.csv")
        blocks.append(f"## {exp}\n\n{len(per)} runs over {len(agg)} tags.\n\n"
                      + A.markdown_table(exp, per, agg, window=args.window) + "\n")
    header = (f"# Results summary\n\nGenerated by `scripts/summarize_all.py` on "
              f"{datetime.datetime.now():%Y-%m-%d %H:%M}. Participation minima are windowed to step <= {args.window}; "
              "peak cosine, kappa and accuracies are over the whole run. `--` means the quantity is not defined for "
              "that tag (no plateau detected, or the run is shorter than the step quoted).\n")
    with open(out_md, "w") as fh:
        fh.write(header + "\n" + "\n".join(blocks) if blocks else header + "\nNo summarizable experiments yet.\n")
    print(f"wrote {out_md} ({done} experiments)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
