#!/usr/bin/env python3
"""Generate focused manuscript tables from preserved, complete result summaries.

The source CSVs retain every condition, including those shown only in figures.
Selection here follows scientific comparisons, never outcome thresholds.
"""
from pathlib import Path
import json
import sys
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from cmc.cifar_reporting import TABLE_CONDITIONS, load_records, summarize
SOURCES = ROOT / 'results/paper_summary_sources'
OUT = ROOT / 'paper/tables'
ROW_SOURCES = {}


def frame(experiment):
    return pd.read_csv(SOURCES / f'{experiment}__summary.csv').set_index('tag')


def value(row, key, decimals=2):
    mean, sd = row.get(key + '_mean', np.nan), row.get(key + '_sd', np.nan)
    if not np.isfinite(mean):
        return '--'
    if decimals == 'scientific':
        exponent = int(np.floor(np.log10(abs(mean)))) if mean else 0
        if abs(float(f'{mean / 10.0**exponent:.2g}')) >= 10:   # e.g. 9.996e-1 rounds to 1.0e0, not 10e-1
            exponent += 1
        scale = 10.0**exponent
        spread = f'({sd/scale:.2g})' if np.isfinite(sd) else ''
        return rf'${mean/scale:.2g}{spread}\!\times10^{{{exponent}}}$'
    spec = f'.{decimals}f'
    spread = rf'\pm{sd:{spec}}' if np.isfinite(sd) else ''
    return f'${mean:{spec}}{spread}$'


def sample_pm(values, decimals=2):
    v = pd.Series(values, dtype=float).dropna()
    if len(v) == 0:
        return '--'
    spread = rf'\pm{v.std():.{decimals}f}' if len(v) > 1 else ''
    return f'${v.mean():.{decimals}f}{spread}$'


def table(name, label, caption, headers, rows, sources):
    lines = [r'% Generated by scripts/supplement_tables.py.',
             r'\begin{table}[t]\centering\footnotesize\setlength{\tabcolsep}{3.5pt}',
             rf'\caption{{{caption}}}\label{{{label}}}',
             r'\begin{tabular}{l' + 'r' * (len(headers) - 1) + r'}\toprule',
             ' & '.join(headers) + r'\\\midrule']
    lines += [' & '.join(map(str, row)) + r'\\' for row in rows]
    lines += [r'\bottomrule\end{tabular}\end{table}']
    (OUT / (name + '.tex')).write_text('\n'.join(lines) + '\n')
    ROW_SOURCES[name] = sources


def main():
    d = frame('E1_headline')
    controls = [('base', 'Plain DFA'), ('bp', 'Backpropagation'),
                ('fa', 'Layerwise FA'), ('aligned', 'Pre-aligned DFA'),
                ('bp_outx12', r'BP, output weights $\times12$'),
                ('center_e', 'Center output error'), ('center_delta', 'Center teaching signal'),
                ('pixcenter', 'Center inputs'), ('frzbias', 'Freeze hidden biases'),
                ('pixcenter_frzbias', 'Center inputs + freeze biases'),
                ('outlr10', 'Faster readout'), ('frzout', 'Frozen readout'),
                ('priorbias', 'Prior-bias initialization'), ('softmax', 'Balanced softmax'),
                ('softmax_imb07', 'Imbalanced softmax'),
                ('softmax_imb07_bp', 'Imbalanced softmax, BP')]
    rows = [[name, int(d.loc[tag, 'n_runs']), value(d.loc[tag], 'maxcos_l3', 3),
             value(d.loc[tag], 'minp_w300_l3', 3), value(d.loc[tag], 'acc_3000', 3)]
            for tag, name in controls]
    table('summary_baseline', 'tab:E1',
          r'MNIST baseline and mean-drive controls. Peak cosine uses the recorded trajectory; participation uses the first 300 updates. Accuracy is measured at step 3000. The frozen-readout control ends at step 1500, so its endpoint is unavailable (--). Softmax rows use globally standardized inputs, while other rows use raw pixels unless input centering is specified. Values are means $\pm$ standard deviations.',
          ['Condition', '$n$', r'Peak $\cos_3$', r'Min. $p_3$', 'Accuracy'], rows,
          [{'experiment': 'E1_headline', 'tag': tag, 'label': name} for tag, name in controls])

    d = frame('E2_master'); rows = []
    for c in [2, 3, 5, 10]:
        row = d.loc[f'C{c}']
        rows.append([c, int(row.n_runs), f'${np.sqrt(c)*(0.5-1/c):.3f}$', value(row, 'ebar0', 3)])
    table('summary_initial_error', 'tab:E2',
          r'Initial mean error under sigmoid outputs as the number of MNIST classes changes. The ideal value assumes a constant prediction of one half. The measured value uses a random readout. Class restriction also changes training-set size; this comparison tests initialization, not later learning speed.',
          ['$C$', '$n$', r'Ideal $\|\bar e_0\|$', r'Measured $\|\bar e_0\|$'], rows,
          [{'experiment': 'E2_master', 'tag': f'C{c}'} for c in [2, 3, 5, 10]])

    d = pd.read_csv(ROOT / 'results/review_20260919/anatomy_matched.csv')
    labels = {'base': 'Plain DFA', 'bp': 'Backpropagation', 'aligned': 'Pre-aligned DFA',
              'center_delta': 'Center teaching signal', 'frzout': 'Frozen readout',
              'g3': 'Feedback gain 3', 'softmax': 'Balanced softmax', 'smimb07': 'Imbalanced softmax'}
    rows = []
    for tag, name in labels.items():
        g = d[d.tag == tag]
        rows.append([name, len(g), sample_pm(g.step, 0), sample_pm(g.energy_drop, 1),
                     sample_pm(g.R_initial), sample_pm(g.R_matched)])
    table('summary_covariance', 'tab:E7',
          r'Covariance amplitude and its normalized statistic at matched layer-3 checkpoints. Within each run, $t_*\ge30$ minimizes covariance energy among checkpoints with a recorded $R_3$. The energy ratio is $\|\Lambda_3(0)\|_F^2/\|\Lambda_3(t_*)\|_F^2$. A large amplitude loss need not imply a comparable loss of normalized covariance. $R_3$ is not held-out accuracy.',
          ['Condition', '$n$', '$t_*$', 'Energy ratio', '$R_3(0)$', '$R_3(t_*)$'], rows,
          [{'source': 'results/review_20260919/anatomy_matched.csv', 'tag': tag} for tag in labels])

    d = pd.read_csv(ROOT / 'results/review_20260919/shift_windows.csv')
    labels = {'shift300': 'DFA, early shift', 'shift300_bp': 'BP, early shift',
              'shift1500': 'DFA, late shift', 'shift1500_bp': 'BP, late shift'}
    rows = []
    for tag, name in labels.items():
        g = d[d.tag == tag]
        rows.append([name, len(g), int(g['shift'].iloc[0]), sample_pm(g.cos_pre),
                     sample_pm(g.cos_post), sample_pm(g.error_first, 3), sample_pm(g.error_fifty, 3)])
    table('summary_shift', 'tab:E8',
          r'Class-prior shifts in the MNIST softmax MLP described in Appendix~\ref{app:label_shift}. Peak cosine uses the 100 updates before and 300 updates after the shift. Error norms use the first shifted training batch and the batch 50 updates later. The fixed validation probe retains its pre-shift distribution.',
          ['Condition', '$n$', 'Shift', 'Cos. before', 'Cos. after', r'$\|\bar e\|$: first', '+50'], rows,
          [{'source': 'results/review_20260919/shift_windows.csv', 'tag': tag} for tag in labels])

    d = frame('E9_headinit')
    controls = [('mse_ctr', 'Centered squared error, random readout'),
                ('mse_ctr_w0', 'Centered squared error, zero readout'),
                ('mse_ctr_w0_bp', 'Same zero readout, BP'),
                ('mse_w0', 'Uncentered squared error, zero readout'),
                ('sigmoid_w0', 'Sigmoid, zero readout'), ('softmax_w0', 'Softmax, zero readout')]
    rows = [[name, int(d.loc[tag, 'n_runs']), value(d.loc[tag], 'ebar0', 3),
             value(d.loc[tag], 'maxcos_l3', 3), value(d.loc[tag], 'minp_w300_l3', 3)] for tag, name in controls]
    table('summary_readout_init', 'tab:E9',
          r'Readout initialization and target centering in the baseline architecture. Zero readout means zero output weights; sigmoid predictions are then one half at initialization. Peak cosine uses the 2000-update trajectory, and participation minima use the first 300 updates.',
          ['Readout and targets', '$n$', r'Initial $\|\bar e\|$', 'Peak cosine', 'Min. $p_3$'], rows,
          [{'experiment': 'E9_headinit', 'tag': tag, 'label': name} for tag, name in controls])

    d = frame('E10_nonsat')
    protocols = [('lr1e4', r'$10^{-4}$', 'Plain DFA'),
                 ('lr1e4_centere', r'$10^{-4}$', 'Center error'),
                 ('lr3e4', r'$3\times10^{-4}$', 'Plain DFA'),
                 ('lr3e4_centere', r'$3\times10^{-4}$', 'Center error'),
                 ('lr3e4_centere_outlr10', r'$3\times10^{-4}$', 'Center error + faster readout'),
                 ('lr1e3_bp', r'$10^{-3}$', 'Backpropagation'),
                 ('lr1e3_priorbias', r'$10^{-3}$', 'Prior-bias initialization'),
                 ('lr1e3_centere_outlr10', r'$10^{-3}$', 'Center error + faster readout'),
                 ('lr1e3_centere_pixcenter', r'$10^{-3}$', 'Center error + inputs')]
    rows = [[name, rate] + [value(d.loc[f'{act}_{suffix}'], 'loss_final', 'scientific')
                            for act in ['relu', 'gelu', 'linear']]
            for suffix, rate, name in protocols]
    table('summary_instability', 'tab:E10',
          r'Final loss with non-saturating units after 3000 updates. All 27 activation--protocol combinations are retained, with three seeds each. Entries give the mean (standard deviation) in scientific notation. The hidden learning rate is shown; a faster readout uses ten times that rate. Large finite losses indicate instability and are not nonfinite early stops. The constant-predictor reference is about $\numPriorLoss$.',
          ['Protocol', r'$\eta_{\rm hid}$', 'ReLU loss', 'GELU loss', 'Linear loss'], rows,
          [{'experiment': 'E10_nonsat', 'tag': f'{act}_{suffix}'}
           for suffix, _, _ in protocols for act in ['relu', 'gelu', 'linear']])

    cifar = summarize(load_records(ROOT / 'results'))
    rows, sources = [], []
    for exp, tag, name in TABLE_CONDITIONS:
        group = cifar[(cifar.experiment == exp) & (cifar.tag == tag)]
        rows.append([name, len(group), sample_pm(group.maxcos, 3),
                     sample_pm(group.minp, 3), sample_pm(group.acc_3000, 3)])
        sources.append(dict(source='results/cifar_reporting/trajectories.csv', experiment=exp,
                            tag=tag, layer=int(group.layer.iloc[0]), label=name,
                            runs=group.run.tolist()))
    table('summary_cifar', 'tab:cifar_controls',
          r'CIFAR-10 controls. Conditions shared with Figure~\ref{fig:cifar} use the same runs and layers. CNN geometry uses hidden block 3, the 128-unit fully connected layer after two convolutional blocks; MLP geometry uses layer 1. Entries average per-run peak cosine over 4000 updates and minimum participation within 300 updates, with sample standard deviations. Accuracy is measured at step 3000. Softmax CNNs use globally standardized inputs. Other rows use raw pixels except the stated centering or standardization controls. Imbalanced accuracy should be read with Table~\ref{tab:review_imbalance}.',
          ['Condition', '$n$', 'Peak cosine', 'Min. participation', 'Accuracy'], rows, sources)
    d = pd.read_csv(ROOT / 'results/revision_per_run.csv')
    d = d[d.family == 'E15_cifar100']
    labels = [('sigmoid_bce', 'Sigmoid, DFA'), ('sigmoid_bce_bp', 'Sigmoid, BP'),
              ('softmax_ce', 'Softmax, DFA'), ('softmax_ce_bp', 'Softmax, BP')]
    rows = []
    for tag, name in labels:
        g = d[d.tag == tag]
        rows.append([name, len(g), sample_pm(g.mean_error_init, 3),
                     sample_pm(g.maxcos, 3), sample_pm(g.minp, 3), sample_pm(g.acc_final, 3)])
    table('summary_cifar100', 'tab:cifar100',
          r'CIFAR-100 readouts in the three-layer tanh MLP under DFA and matched BP (same initializations and minibatches). High peak cosine also occurs under BP on these uncentered images; participation separates the rules, and sigmoid outputs concentrate gate energy most. Participation minima use the first 300 updates; peak cosine and final accuracy use the 3000-update run. Accuracy remains low for both rules after 3000 updates at this learning rate, so these runs test the early transient rather than final performance.',
          ['Readout, rule', '$n$', r'Initial $\|\bar e\|$', 'Peak cosine', 'Min. $p_3$', 'Accuracy'], rows,
          [{'source': 'results/revision_per_run.csv', 'family': 'E15_cifar100', 'tag': tag} for tag, _ in labels])
    (SOURCES / 'paper_rows.json').write_text(json.dumps(ROW_SOURCES, indent=2) + '\n')
    print(f'Generated {len(ROW_SOURCES)} focused tables; row-to-source mapping saved.')


if __name__ == '__main__':
    main()
